name: "MATLAB: test and coverage"

# Installs
# - MATLAB github action
# - MOXunit
# - MOcov
# Get test data
# cd into .github/workflows
# run .github/workflows/tests_matlab.m
# If tests pass, uploads coverage to codecov

on:
  push:
    branches: ["master", "main", "dev"]
  pull_request:
    branches: ["*"]

jobs:
  matlab_tests:

    strategy:
      matrix:
        os: [ubuntu-latest] # "macos-latest" or "windows-latest" don't work (yet?)
        matlab-version: ["R2020a"] # add more versions if needed: "R2021a"
      fail-fast: false  # Don't cancel all jobs if one fails

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install MATLAB ${{ matrix.matlab-version }}
        uses: matlab-actions/setup-matlab@v1.0.1
        with:
          release: ${{ matrix.matlab-version }}

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Moxunit and MOcov
        run: |
          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
          git clone https://github.com/MOcov/MOcov.git --depth 1

      - name: Run tests
        uses: matlab-actions/run-command@v1.0.1
        with:
          command:
            cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows'));
            run run_tests_ci;

      - name: Check logs
        run: |
          cat test_report.log | grep 0
          bash <(curl -s https://codecov.io/bash)

      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml # optional
          flags: matlab # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
